services:
  db:
    image: mysql:9.0.0
    restart: always
    env_file: "env/db.env"
    ports:
      - "9000:3306"
    volumes:
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./db/data
        target: /var/lib/mysql
    networks:
      - main
  app:
    image: rss-feed-app:latest
    build: .
    command: ["python", "-m", "pip", "freeze"]
    restart: always
    env_file: "env/app.env"
    networks:
      - main

networks:
  main:
